services:
  website-builder:
    container_name: website-builder
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./website:/app
      - website-dist:/app/dist
    command: >
      sh -c "
        cd /app &&
        bun install &&
        bun run build
      "
    networks:
      - caddy
  caddy:
    container_name: caddy
    image: caddy:2.11
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    env_file:
      - .env
    volumes:
      - ./caddy/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

      - website-dist:/var/www/website:ro
      - docs-dist:/var/www/docs:ro
    # mem_limit: 256m
    # cpu_shares: 512
    networks:
      - caddy
      - hsjs
  anubis:
    image: ghcr.io/techarohq/anubis:v1.24.0
    restart: unless-stopped
    pull_policy: always
    environment:
      BIND: ":3000"
      TARGET: http://caddy:8080
    networks:
      - caddy
  pihole:
    image: pihole/pihole:2025.11.1
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2000:80/tcp"
      - "2001:443/tcp"
      - "67:67/udp"
      - "123:123/udp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    environment:
      TZ: "Europe/Oslo"
      FTLCONF_dns_upstreams: 1.1.1.1;8.8.8.8;8.8.4.4

      FTLCONF_webserver_api_password: ${PIHOLE_ADMIN_PASSWORD}
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - ./etc-pihole/:/etc/piehole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
networks:
  caddy:
    name: caddy
  hsjs:
    external: true
volumes:
  caddy_data:
  caddy_config:
  website-dist:
  docs-dist:
    external: true
